/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class snake_mp_util_JavaCallCTools */

#ifndef _Included_snake_mp_util_JavaCallCTools
#define _Included_snake_mp_util_JavaCallCTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     snake_mp_util_JavaCallCTools
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_snake_mp_util_JavaCallCTools_init
  (JNIEnv *, jobject);

/*
 * Class:     snake_mp_util_JavaCallCTools
 * Method:    get_reply
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_snake_mp_util_JavaCallCTools_get_1reply
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
